# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'counter.ui'
#
# Created by: PyQt5 UI code generator 5.14.2
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("myapp")
        Form.resize(419, 509)
        self.pushButton = QtWidgets.QPushButton(Form)
        self.pushButton.setGeometry(QtCore.QRect(30, 220, 161, 41))
        self.pushButton.setObjectName("pushButton")
        self.pushButton_2 = QtWidgets.QPushButton(Form)
        self.pushButton_2.setGeometry(QtCore.QRect(220, 220, 161, 41))
        self.pushButton_2.setObjectName("pushButton_2")
        self.pushButton_3 = QtWidgets.QPushButton(Form)
        self.pushButton_3.setGeometry(QtCore.QRect(30, 440, 161, 41))
        self.pushButton_3.setObjectName("pushButton_3")
        self.pushButton_4 = QtWidgets.QPushButton(Form)
        self.pushButton_4.setGeometry(QtCore.QRect(220, 440, 71, 41))
        self.pushButton_4.setObjectName("pushButton_4")
        self.pushButton_5 = QtWidgets.QPushButton(Form)
        self.pushButton_5.setGeometry(QtCore.QRect(310, 440, 71, 41))
        self.pushButton_5.setObjectName("pushButton_5")
        self.pushButton_6 = QtWidgets.QPushButton(Form)
        self.pushButton_6.setGeometry(QtCore.QRect(220, 380, 71, 41))
        self.pushButton_6.setObjectName("pushButton_6")
        self.pushButton_7 = QtWidgets.QPushButton(Form)
        self.pushButton_7.setGeometry(QtCore.QRect(310, 380, 71, 41))
        self.pushButton_7.setObjectName("pushButton_7")
        self.pushButton_8 = QtWidgets.QPushButton(Form)
        self.pushButton_8.setGeometry(QtCore.QRect(220, 320, 71, 41))
        self.pushButton_8.setObjectName("pushButton_8")
        self.pushButton_9 = QtWidgets.QPushButton(Form)
        self.pushButton_9.setGeometry(QtCore.QRect(310, 320, 71, 41))
        self.pushButton_9.setObjectName("pushButton_9")
        self.pushButton_10 = QtWidgets.QPushButton(Form)
        self.pushButton_10.setGeometry(QtCore.QRect(220, 270, 71, 41))
        self.pushButton_10.setObjectName("pushButton_10")
        self.pushButton_11 = QtWidgets.QPushButton(Form)
        self.pushButton_11.setGeometry(QtCore.QRect(310, 270, 71, 41))
        self.pushButton_11.setObjectName("pushButton_11")
        self.pushButton_12 = QtWidgets.QPushButton(Form)
        self.pushButton_12.setGeometry(QtCore.QRect(30, 270, 71, 41))
        self.pushButton_12.setObjectName("pushButton_12")
        self.pushButton_13 = QtWidgets.QPushButton(Form)
        self.pushButton_13.setGeometry(QtCore.QRect(120, 270, 71, 41))
        self.pushButton_13.setObjectName("pushButton_13")
        self.pushButton_14 = QtWidgets.QPushButton(Form)
        self.pushButton_14.setGeometry(QtCore.QRect(30, 320, 71, 41))
        self.pushButton_14.setObjectName("pushButton_14")
        self.pushButton_15 = QtWidgets.QPushButton(Form)
        self.pushButton_15.setGeometry(QtCore.QRect(120, 320, 71, 41))
        self.pushButton_15.setObjectName("pushButton_15")
        self.pushButton_16 = QtWidgets.QPushButton(Form)
        self.pushButton_16.setGeometry(QtCore.QRect(30, 380, 71, 41))
        self.pushButton_16.setObjectName("pushButton_16")
        self.pushButton_17 = QtWidgets.QPushButton(Form)
        self.pushButton_17.setGeometry(QtCore.QRect(120, 380, 71, 41))
        self.pushButton_17.setObjectName("pushButton_17")
        self.textBrowser = QtWidgets.QTextBrowser(Form)
        self.textBrowser.setGeometry(QtCore.QRect(35, 10, 351, 192))
        self.textBrowser.setObjectName("textBrowser")

        self.retranslateUi(Form)
        self.pushButton_16.clicked.connect(Form.Button_1)
        self.pushButton.clicked.connect(Form.clear)
        self.pushButton_17.clicked.connect(Form.Button_2)
        self.pushButton_6.clicked.connect(Form.Button_3)
        self.pushButton_14.clicked.connect(Form.Button_4)
        self.pushButton_15.clicked.connect(Form.Button_5)
        self.pushButton_8.clicked.connect(Form.Button_6)
        self.pushButton_12.clicked.connect(Form.Button_7)
        self.pushButton_13.clicked.connect(Form.Button_8)
        self.pushButton_10.clicked.connect(Form.Button_9)
        self.pushButton_3.clicked.connect(Form.Button_0)
        self.pushButton_5.clicked.connect(Form.Button_add)
        self.pushButton_9.clicked.connect(Form.Button_mul)
        self.pushButton_11.clicked.connect(Form.Button_div)
        self.pushButton_7.clicked.connect(Form.Button_sub)
        self.pushButton_2.clicked.connect(Form.equal)
        self.pushButton_4.clicked.connect(Form.Button_point)
        QtCore.QMetaObject.connectSlotsByName(Form)
        Form.setTabOrder(self.pushButton_16, self.pushButton_17)
        Form.setTabOrder(self.pushButton_17, self.pushButton_6)
        Form.setTabOrder(self.pushButton_6, self.pushButton_14)
        Form.setTabOrder(self.pushButton_14, self.pushButton_15)
        Form.setTabOrder(self.pushButton_15, self.pushButton_8)
        Form.setTabOrder(self.pushButton_8, self.pushButton_12)
        Form.setTabOrder(self.pushButton_12, self.pushButton_13)
        Form.setTabOrder(self.pushButton_13, self.pushButton_10)
        Form.setTabOrder(self.pushButton_10, self.pushButton_3)
        Form.setTabOrder(self.pushButton_3, self.pushButton_4)
        Form.setTabOrder(self.pushButton_4, self.pushButton_5)
        Form.setTabOrder(self.pushButton_5, self.pushButton_7)
        Form.setTabOrder(self.pushButton_7, self.pushButton_9)
        Form.setTabOrder(self.pushButton_9, self.pushButton_11)
        Form.setTabOrder(self.pushButton_11, self.pushButton_2)
        Form.setTabOrder(self.pushButton_2, self.pushButton)
        Form.setTabOrder(self.pushButton, self.textBrowser)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "myapp"))
        self.pushButton.setText(_translate("Form", "Clear"))
        self.pushButton_2.setText(_translate("Form", "="))
        self.pushButton_3.setText(_translate("Form", "0"))
        self.pushButton_4.setText(_translate("Form", "."))
        self.pushButton_5.setText(_translate("Form", "+"))
        self.pushButton_6.setText(_translate("Form", "3"))
        self.pushButton_7.setText(_translate("Form", "-"))
        self.pushButton_8.setText(_translate("Form", "6"))
        self.pushButton_9.setText(_translate("Form", "*"))
        self.pushButton_10.setText(_translate("Form", "9"))
        self.pushButton_11.setText(_translate("Form", "/"))
        self.pushButton_12.setText(_translate("Form", "7"))
        self.pushButton_13.setText(_translate("Form", "8"))
        self.pushButton_14.setText(_translate("Form", "4"))
        self.pushButton_15.setText(_translate("Form", "5"))
        self.pushButton_16.setText(_translate("Form", "1"))
        self.pushButton_17.setText(_translate("Form", "2"))
